# Custom Language File for Launcher Customizer

[ejs.app]
title = "Steam-MC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/p-star-90/Steam-MC_Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/p-star-90/Steam-MC_Launcher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR LE LAUNCHER STEAM-MC"
welcomeDescription = "Bienvenu sur le serveur Minecraft Survie dans un monde steampunk"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de Steam-MC."
